logging:
  level: INFO
  path: ./outputs/logs


mode: multi_task

tasks:
  - Mortality
  - ARF
  - Bleed


# pos_weight is used for weighting the positive class in the loss function, especially in cases of class imbalance.
#pos_weights:
#  Mortality: 10 
#  ARF: 4.0         # 5% positive
#  Bleed: 2.5       # 8% positive

pos_weights: {}  # ← همه weights میشن 1.0

paths:
## INPUTS
  prepared_data: '/Users/gkc492/Documents/PHDJourney/Projects/CoreBehrt_OOH/multi_task_learning/outputs/prepared_data'
  pretrain_model: '/Users/gkc492/Documents/PHDJourney/Projects/CoreBehrt_OOH/outputs/pretraining'

  
  # restart_model: ... # Use for restarting from checkpoint
      
## OUTPUTS
  model: '/Users/gkc492/Documents/PHDJourney/Projects/CoreBehrt_OOH/multi_task_learning/outputs/model'

  #./outputs/finetuning # Save model/outputs to this folder
  #runs: ./outputs/pretraining # Use for generating a new modeal folder
  
evaluate: false # evaluate best model on test sets
      
model:
  cls:
    _target_: ehr2vec.model.heads.ClassifierGRU
    bidirectional: true
    

trainer_args:

  save_representations: true
  save_labels: true
  representation_types: ["mean", "cls", "max", "last"]
  task: finetune
    
    
  loss_function: null

  #loss_function:
  #  _target_: corebehrt.modules.trainer.losses.FocalLoss
  #  alpha: 0.75
  #  gamma: 2.0
  #  use_pos_weight: false
    
       
  sampler_function: 
    _target_: corebehrt.modules.trainer.utils.Sampling.effective_n_samples 
    #function to calculate sample weights. ----Possible options: inverse_sqrt and effective_n_samples
    #_target_: corebehrt.modules.trainer.utils.Sampling.inverse_sqrt    
   
  loss_weight_function: 
    _target_: corebehrt.modules.trainer.utils.PositiveWeight.effective_n_samples 
    # function to calculate positive weights. Possible options: sqrt and effective_n_samples

  batch_size: 64  #128
  val_batch_size: 256
  effective_batch_size: 512
  
  epochs: 10 #18 for mor
  info: true
  gradient_clip: 
    clip_value: 1     # 0.25 
  shuffle: true
  checkpoint_frequency: 1
  early_stopping: 10           #4 for Mor      
  stopping_criterion: roc_auc   #pr_auc   
  

  # Freezing options
  n_layers_to_freeze: 4
  unfreeze_on_plateau: true  #true  # unfreeze all layers if the performance is less than plateau_threshold 
  #unfreeze_at_epoch: 8   #10 # if unfrezze_on_plateau is true, whichever condition is met first
  plateau_threshold: 0.003 
  reset_patience_after_unfreeze: true # reset early stopping counter after unfreezing

optimizer:
  lr: 1e-5   #2e-5
  eps: 1e-8
  weight_decay: 0.01 

scheduler:
  _target_: transformers.get_linear_schedule_with_warmup
  num_warmup_steps: 400 
  num_training_steps: 6000  #16320 #5840
#steps_per_epoch = 52212 / 512 ≈ 102
#102 × 40 ≈ 4080

#
metrics:
  accuracy:
    _target_: corebehrt.modules.monitoring.metrics.Accuracy
    threshold: 0.05
  roc_auc:
    _target_: corebehrt.modules.monitoring.metrics.ROC_AUC
  pr_auc:
    _target_: corebehrt.modules.monitoring.metrics.PR_AUC
  precentage_positives:
    _target_: corebehrt.modules.monitoring.metrics.Percentage_Positives

  mean_probability:
    _target_: corebehrt.modules.monitoring.metrics.Mean_Probability
  true_positives:
    _target_: corebehrt.modules.monitoring.metrics.True_Positives

  true_negatives:
    _target_: corebehrt.modules.monitoring.metrics.True_Negatives
  false_positives:
    _target_: corebehrt.modules.monitoring.metrics.False_Positives

  false_negatives:
    _target_: corebehrt.modules.monitoring.metrics.False_Negatives
  
  

 
