# evaluate_heldout_mt.yaml
logging:
  level: INFO
  path: ./outputs/logs

mode: multi_task

tasks:
  - Mortality
  - ARF
  - Bleed

paths:
  model: 'researcher_data:Zahra/032026/CoreBehrt_OOT/MDPS/MLT_MAB/2_Finetune/Model_focal_v1'

  folds_dir: 'researcher_data:Zahra/032026/CoreBehrt_OOT/MDPS/MLT_MAB/2_Finetune/Data/PrepareData'

  test_data_dir: 'researcher_data:Zahra/032026/CoreBehrt_OOT/MDPS/MLT_MAB/3_Heldout/Data/PrepareData'
  
  predictions: 'researcher_data:Zahra/032026/CoreBehrt_OOT/MDPS/MLT_MAB/3_Heldout/Predictions'

test_batch_size: 128
return_embeddings: true

metrics:
  roc_auc:
    _target_: sklearn.metrics.roc_auc_score
  pr_auc:
    _target_: sklearn.metrics.average_precision_score