logging:
  level: INFO
  path: ./outputs/logs

paths:
  model: "dummy"  
  folds_dir: "dummy"    # "researcher_data:Zahra/CoreBehrt/MDP/3_Finetune/ARF/Data/FinetuneData/811"     #Finetune Data
  test_data_dir:  "dummy"   #"researcher_data:Zahra/CoreBehrt/MDP/4_Evaluate/ARF/Data/Heldout_Data/811"  

  run_name: "evaluate"

  predictions: "researcher_data:Zahra/032026/CoreBehrt_OOT/MD/3_Holdout/Mortality/Predictions"

  

test_batch_size: 128

return_embeddings: True

metrics:
  roc_auc: 
    _target_: sklearn.metrics.roc_auc_score
  pr_auc: 
    _target_: sklearn.metrics.average_precision_score

save_info: 
  sequence_length: 
    _target_: corebehrt.main.helper.evaluate_finetune.get_sequence_length