logging:
  level: INFO
  path: ./outputs/logs

paths:
  model: "dummy"  
  folds_dir: "dummy"
  test_data_dir: "dummy" 
  run_name: "evaluate"

  predictions: "researcher_data:Zahra/032026/Xgboost_OOT/MDPS/ARF/Evalutation" 

return_feature_importance:
  importance_type: "gain"

metrics:
  roc_auc: 
    _target_: sklearn.metrics.roc_auc_score
  pr_auc: 
    _target_: sklearn.metrics.average_precision_score